### ISSUE TITLE
bots slightly bypassing?

### ISSUE THREAD

**Issue by merpdotcom** [collective/collective.emailconfirmationregistration#2] opened 2015-07-02 12:41 UTC

**Comment by merpdotcom** [comment] 2015-07-02 12:44
Hey there, thought I would provide a status update. Plone 4.3.6 (was 4.3.5). 
While nothing showing up in the user list, when I load the Site Setup > Users and Groups page (/@@usergroup-userprefs), the event.log churns out something a little concerning now:

---

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Darnell

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Santos

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Arden

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jina

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Russell

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Chante

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Mandy

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Dallas

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Cathy

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Tanya

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Georgia

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Shad

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jannette

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Lilly

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Daniele

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Tomoko

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Ivory

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Cindi

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Geneva

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jere

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: LawrenceHo

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: EdwardPype

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Josef

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Veronique

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Myron

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Kristie

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Emerson

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Lloyd

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Earl

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jerrold

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Micah

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Hai

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Marquis

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Broderick

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Aisha

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Tracee

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Shelia

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Vernita

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Polly

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Gerard

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Marta

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Chang

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Gene

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Pedro

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Ezra

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Bernadine

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Dixie

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Glenna

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Sol

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jacquie

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Kirby

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Virgil

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Pasquale

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Roxana

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Paul

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Trinidad

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Vince

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Ebony

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Laurene

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Darnell

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Santos

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Arden

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jina

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Russell

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Chante

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Mandy

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Dallas

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Cathy

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Tanya

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Georgia

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Shad

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jannette

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Lilly

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Daniele

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Tomoko

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Ivory

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Cindi

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Geneva

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jere

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: LawrenceHo

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: EdwardPype

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Josef

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Veronique

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Myron

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Kristie

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Emerson

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Lloyd

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Earl

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jerrold

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Micah

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Hai

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Marquis

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Broderick

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Aisha

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Tracee

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Shelia

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Vernita

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Polly

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Gerard

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Marta

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Chang

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Gene

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Pedro

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Ezra

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Bernadine

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Dixie

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Glenna

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Sol

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Jacquie

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Kirby

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Virgil

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Pasquale

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Roxana

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Paul

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Trinidad

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Vince

## 2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Ebony

2015-07-02T05:40:12 WARNING plone.app.controlpanel Skipped user without principal object: Laurene

What do you think?
Should I crank the security back up to require recaptcha on both pages now, instead of just the initial page? 
Let me know. Thanks.
emailconfirmationregistration version: 1.1.0b2

**Comment by vangheem** [comment] 2015-07-02 12:55
Could this be an artifact of old users that were created, deleted, but maybe weren't fully deleted?

If user objects aren't there, this product is working correctly and you shouldn't need to add an additional recaptcha. This product prevents user objects from ever being created.

I tend to think this is an artifact of something done previously.

Can you go to /manage -> acl_users -> source_users and see if there is junk there?

reference in code to log:
https://github.com/plone/plone.app.controlpanel/blob/2.2.x/plone/app/controlpanel/usergroups.py#L229

**Comment by merpdotcom** [comment] 2015-07-02 12:59
I don't see anything in source_users other than the single valid account.

**Comment by merpdotcom** [comment] 2015-07-02 13:00
Is there some way to clean those old ones out so I can know if any new ones show up?

**Comment by merpdotcom** [comment] 2015-07-02 13:06
Hmmm, seems to be only the tolkienmoot.org website. The several other sites that were up when we started adding this product, aren't generating the same logs at all. All on the same instance.

**Comment by vangheem** [comment] 2015-07-02 13:06
You'll know if any new ones show by looking in the places you're already looking.

However, it's really annoying to get your log spammed with this.

I really don't know how to tell you at this point how to clean it because I don't know how it happened in the first place or where the real inconsistency has occurred.

**Comment by merpdotcom** [comment] 2015-07-02 13:07
Ok. Well, I thought I would let you know. I'll watch to see if any new ones get added and let you know. You are right about the annoying spamming, but if only the one site, and it if doesn't get worse, then I can start a new fresh version over if I have to. I will keep an eye on it and let you know if any changes occur. Thanks again!

**Comment by mauritsvanrees** [comment] 2015-09-09 22:31
If you delete users directly in the ZMI in acl_users, then some stuff gets left behind.  There will at least be orphaned records in portal_memberdata. Go can go there in the ZMI, go to the Contents tab, and click 'Prune orphaned member records'.

It seems there are more places, but that one may help already.

Note that you may easily have at least one orphaned record always for a root zope user. Oh, sneaky:
- login as root zope user
- go to the personal-information form in Plone and fill in at least an email address
- prune the records in portal_memberdata
- your personal information is now gone...

**Comment by vangheem** [comment] 2015-09-10 17:45
Duplicate of https://github.com/collective/collective.emailconfirmationregistration/issues/3

**Closed as completed by vangheem** 2015-09-10 17:45 UTC
